// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.safelink.defs` namespace.
pub type ActionType = String;
///An event for URL safety decisions
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct EventData {
    pub action: ActionType,
    ///Optional comment about the decision
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub comment: core::option::Option<String>,
    pub created_at: crate::types::string::Datetime,
    ///DID of the user who created this rule
    pub created_by: crate::types::string::Did,
    pub event_type: EventType,
    ///Auto-incrementing row ID
    pub id: i64,
    pub pattern: PatternType,
    pub reason: ReasonType,
    ///The URL that this rule applies to
    pub url: String,
}
pub type Event = crate::types::Object<EventData>;
pub type EventType = String;
pub type PatternType = String;
pub type ReasonType = String;
///Input for creating a URL safety rule
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct UrlRuleData {
    pub action: ActionType,
    ///Optional comment about the decision
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub comment: core::option::Option<String>,
    ///Timestamp when the rule was created
    pub created_at: crate::types::string::Datetime,
    ///DID of the user added the rule.
    pub created_by: crate::types::string::Did,
    pub pattern: PatternType,
    pub reason: ReasonType,
    ///Timestamp when the rule was last updated
    pub updated_at: crate::types::string::Datetime,
    ///The URL or domain to apply the rule to
    pub url: String,
}
pub type UrlRule = crate::types::Object<UrlRuleData>;
