// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.feedback.main` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Timestamp when the feedback was provided.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<crate::types::string::Datetime>,
    ///True if the user endorsed the interaction/peer, false otherwise.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub endorsement: core::option::Option<bool>,
    /// Was the feedback apprecatied
    pub liked: core::option::Option<bool>,
    ///The DID of the user who was interacted with.
    pub interacted_with_did: crate::types::string::Did,
    ///Reference to the specific interaction (chat, beacon, mentor intro).
    pub interaction_ref: crate::com::atproto::repo::strong_ref::Main,
    ///Response to the one-question check-in.
    pub question_response: String,
}
pub type Record = crate::types::Object<RecordData>;
