// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.chat` namespace.
pub mod message;
#[derive(Debug)]
pub struct Message;
impl crate::types::Collection for Message {
    const NSID: &'static str = "peerlink.chat.message";
    type Record = message::Record;
}
