// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.defs` namespace.
///An interaction has been accepted.
pub const ACCEPTED: &str = "peerlink.defs#accepted";
///A generalized activity event for user feeds.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ActivityData {
    pub actor_did: crate::types::string::Did,
    pub actor_handle: crate::types::string::Handle,
    ///Short summary or content related to the activity.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub content: core::option::Option<String>,
    pub created_at: crate::types::string::Datetime,
    ///Optional reference to the record associated with this activity.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub related_ref: core::option::Option<crate::com::atproto::repo::strong_ref::Main>,
    pub r#type: String,
}
pub type Activity = crate::types::Object<ActivityData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct BeaconData {
    ///Timestamp when the beacon was created.
    pub created_at: crate::types::string::Datetime,
    ///The DID of the user who created the beacon.
    pub did: crate::types::string::Did,
    ///Timestamp when the beacon expires.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub expires_at: core::option::Option<crate::types::string::Datetime>,
    ///The handle of the user who created the beacon.
    pub handle: crate::types::string::Handle,
    ///The message content of the beacon invite.
    pub message: String,
    ///A course subject this beacon is targeting.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub target_course: core::option::Option<String>,
    ///An interest this beacon is targeting.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub target_interest: core::option::Option<String>,
}
pub type Beacon = crate::types::Object<BeaconData>;
///User created a new beacon.
pub const BEACON_CREATED: &str = "peerlink.defs#beaconCreated";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ChatMessageData {
    ///Timestamp when the message was sent.
    pub created_at: crate::types::string::Datetime,
    ///The content of the chat message.
    pub message: String,
    ///The DID of the message sender.
    pub sender_did: crate::types::string::Did,
    ///The handle of the message sender.
    pub sender_handle: crate::types::string::Handle,
}
pub type ChatMessage = crate::types::Object<ChatMessageData>;
///An interaction has been completed.
pub const COMPLETED: &str = "peerlink.defs#completed";
///An interaction has been declined.
pub const DECLINED: &str = "peerlink.defs#declined";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FeedbackData {
    ///Timestamp when the feedback was provided.
    pub created_at: crate::types::string::Datetime,
    ///True if the user endorsed the interaction/peer, false otherwise.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub endorsement: core::option::Option<bool>,
    ///The DID of the user giving feedback.
    pub giver_did: crate::types::string::Did,
    ///The handle of the user giving feedback.
    pub giver_handle: crate::types::string::Handle,
    ///The DID of the user who was interacted with.
    pub interacted_with_did: crate::types::string::Did,
    ///The handle of the user who was interacted with.
    pub interacted_with_handle: crate::types::string::Handle,
    ///Reference to the specific interaction.
    pub interaction_ref: crate::com::atproto::repo::strong_ref::Main,
    ///Response to the one-question check-in.
    pub question_response: String,
}
pub type Feedback = crate::types::Object<FeedbackData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct MentorIntroData {
    ///Expected duration of the introduction in minutes.
    pub duration: i64,
    ///Timestamp when the introduction was requested.
    pub intro_request_at: crate::types::string::Datetime,
    ///The DID of the mentee.
    pub mentee_did: crate::types::string::Did,
    ///The handle of the mentee.
    pub mentee_handle: crate::types::string::Handle,
    ///The DID of the mentor.
    pub mentor_did: crate::types::string::Did,
    ///The handle of the mentor.
    pub mentor_handle: crate::types::string::Handle,
    pub status: String,
}
pub type MentorIntro = crate::types::Object<MentorIntroData>;
///User requested a mentor introduction.
pub const MENTOR_INTRO_REQUEST: &str = "peerlink.defs#mentorIntroRequest";
///User found a new peer match.
pub const NEW_MATCH: &str = "peerlink.defs#newMatch";
///User created a new post.
pub const NEW_POST: &str = "peerlink.defs#newPost";
///An interaction is pending.
pub const PENDING: &str = "peerlink.defs#pending";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct PostData {
    ///Timestamp when this post was created.
    pub created_at: crate::types::string::Datetime,
    ///The DID of the user who made the post.
    pub did: crate::types::string::Did,
    ///The handle of the user who made the post.
    pub handle: crate::types::string::Handle,
    ///The content of the post.
    pub text: String,
}
pub type Post = crate::types::Object<PostData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ProfileData {
    ///The user's arrival date.
    pub arrival_date: crate::types::string::Datetime,
    ///URL to the user's avatar image.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<String>,
    ///Specific campus life needs or preferences.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub campus_life_needs: core::option::Option<Vec<String>>,
    ///The user's country of origin/citizenship.
    pub country: String,
    ///A short bio or description.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///The DID of the user.
    pub did: crate::types::string::Did,
    ///The user's display name.
    pub display_name: String,
    ///The user's handle.
    pub handle: crate::types::string::Handle,
    ///List of the user's hobbies and interests.
    pub hobbies: Vec<String>,
    ///Whether the authenticated user is following this profile.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub is_following: core::option::Option<bool>,
    ///The user's primary language.
    pub language: String,
    ///A calculated match score based on shared interests/courses.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub match_score: core::option::Option<crate::types::LimitedU8<100u8>>,
    ///List of subjects the user is studying.
    pub study_subjects: Vec<String>,
}
pub type Profile = crate::types::Object<ProfileData>;
///User updated their profile.
pub const PROFILE_UPDATE: &str = "peerlink.defs#profileUpdate";
