// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.feedback` namespace.
pub mod main;
#[derive(Debug)]
pub struct Main;
impl crate::types::Collection for Main {
    const NSID: &'static str = "peerlink.feedback.main";
    type Record = main::Record;
}
