// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.getProfile` namespace.
pub const NSID: &str = "peerlink.getProfile";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///The DID of the user to get the profile of.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub did: core::option::Option<crate::types::string::Did>,
    ///The handle of the user to get the profile of.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub handle: core::option::Option<crate::types::string::Handle>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///Feedback given by this user.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub given_feedback: core::option::Option<Vec<crate::peerlink::defs::Feedback>>,
    ///Mentor introductions associated with this user (mentee or mentor).
    pub mentor_connections: Vec<crate::peerlink::defs::MentorIntro>,
    ///Recent posts by this user.
    pub posts: Vec<crate::peerlink::defs::Post>,
    ///The user's PeerLink profile.
    pub profile: crate::peerlink::defs::Profile,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
