// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.mentor` namespace.
pub mod intro;
#[derive(Debug)]
pub struct Intro;
impl crate::types::Collection for Intro {
    const NSID: &'static str = "peerlink.mentor.intro";
    type Record = intro::Record;
}
