// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink` namespace.
pub mod beacon;
pub mod chat;
pub mod defs;
pub mod feedback;
pub mod get_profile;
pub mod mentor;
pub mod post;
pub mod profile;
pub mod search_users;
