// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.profile` namespace.
pub mod user;
#[derive(Debug)]
pub struct User;
impl crate::types::Collection for User {
    const NSID: &'static str = "peerlink.profile.user";
    type Record = user::Record;
}
