// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.searchUsers` namespace.
pub const NSID: &str = "peerlink.searchUsers";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///Filter by country of origin.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub country: core::option::Option<String>,
    ///Filter by shared interest.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub interest: core::option::Option<String>,
    ///Filter by spoken language.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub language: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
    ///Offset for pagination into the result set.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub offset: core::option::Option<i64>,
    ///General search query against display name, handle, interests, subjects.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub q: core::option::Option<String>,
    ///Filter by shared study subject/course.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub subject: core::option::Option<String>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    ///The next offset to use for pagination (result of limit + offset).
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub offset: core::option::Option<i64>,
    pub users: Vec<crate::peerlink::defs::Profile>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
