// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.bookmark` namespace.
pub mod create_bookmark;
pub mod defs;
pub mod delete_bookmark;
pub mod get_bookmarks;
