// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.chat.message` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Timestamp when the message was sent.
    pub created_at: crate::types::string::Datetime,
    ///The content of the chat message.
    pub message: String,
    ///The DID of the message receiver.
    pub receiver_did: crate::types::string::Did,
    ///The DID of the message sender.
    pub sender_did: crate::types::string::Did,
}
pub type Record = crate::types::Object<RecordData>;
