// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.temp` namespace.
pub mod add_reserved_handle;
pub mod check_handle_availability;
pub mod check_signup_queue;
pub mod dereference_scope;
pub mod fetch_labels;
pub mod request_phone_verification;
pub mod revoke_account_credentials;
