// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.unspecced.getAgeAssuranceState` namespace.
pub const NSID: &str = "app.bsky.unspecced.getAgeAssuranceState";
pub type Output = crate::app::bsky::unspecced::defs::AgeAssuranceState;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
