// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.beacon.main` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Timestamp when the beacon was created.
    pub created_at: crate::types::string::Datetime,
    ///Timestamp when the beacon expires.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub expires_at: core::option::Option<crate::types::string::Datetime>,
    ///The message content of the beacon invite.
    pub message: String,
    ///A course subject this beacon is targeting.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub target_course: core::option::Option<String>,
    ///An interest this beacon is targeting.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub target_interest: core::option::Option<String>,
}
pub type Record = crate::types::Object<RecordData>;
