// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.mentor.intro` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Expected duration of the introduction in minutes (e.g., 20).
    pub duration: core::num::NonZeroU64,
    ///Timestamp when the introduction was requested.
    pub intro_request_at: crate::types::string::Datetime,
    ///The DID of the mentee requesting the introduction.
    pub mentee_did: crate::types::string::Did,
    ///The DID of the mentor being introduced to.
    pub mentor_did: crate::types::string::Did,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub status: core::option::Option<String>,
}
pub type Record = crate::types::Object<RecordData>;
