// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.post.main` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///Timestamp when this post was originally created.
    pub created_at: crate::types::string::Datetime,
    ///DIDs of users mentioned in the post.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub mentions: core::option::Option<Vec<crate::types::string::Did>>,
    ///Reference to the post this is a reply to.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub reply_to: core::option::Option<crate::com::atproto::repo::strong_ref::Main>,
    ///The content of the post.
    pub text: String,
    /// The labels behind each post
    pub labels: core::option::Option<Vec<String>>,
    ///Topics included
    pub topics: [Labels; 9],
}

#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
enum Labels {}

pub type Record = crate::types::Object<RecordData>;
