// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `com.atproto.moderation.defs` namespace.
///Appeal a previously taken moderation action
pub const REASON_APPEAL: &str = "com.atproto.moderation.defs#reasonAppeal";
///Misleading identity, affiliation, or content. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingOther`.
pub const REASON_MISLEADING: &str = "com.atproto.moderation.defs#reasonMisleading";
///Reports not falling under another report category. Prefer new lexicon definition `tools.ozone.report.defs#reasonRuleOther`.
pub const REASON_OTHER: &str = "com.atproto.moderation.defs#reasonOther";
///Rude, harassing, explicit, or otherwise unwelcoming behavior. Prefer new lexicon definition `tools.ozone.report.defs#reasonHarassmentOther`.
pub const REASON_RUDE: &str = "com.atproto.moderation.defs#reasonRude";
///Unwanted or mislabeled sexual content. Prefer new lexicon definition `tools.ozone.report.defs#reasonSexualUnlabeled`.
pub const REASON_SEXUAL: &str = "com.atproto.moderation.defs#reasonSexual";
///Spam: frequent unwanted promotion, replies, mentions. Prefer new lexicon definition `tools.ozone.report.defs#reasonMisleadingSpam`.
pub const REASON_SPAM: &str = "com.atproto.moderation.defs#reasonSpam";
pub type ReasonType = String;
///Direct violation of server rules, laws, terms of service. Prefer new lexicon definition `tools.ozone.report.defs#reasonRuleOther`.
pub const REASON_VIOLATION: &str = "com.atproto.moderation.defs#reasonViolation";
///Tag describing a type of subject that might be reported.
pub type SubjectType = String;
