// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.safelink` namespace.
pub mod add_rule;
pub mod defs;
pub mod query_events;
pub mod query_rules;
pub mod remove_rule;
pub mod update_rule;
