// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `tools.ozone.report.defs` namespace.
///Appeal a previously taken moderation action
pub const REASON_APPEAL: &str = "tools.ozone.report.defs#reasonAppeal";
///Child sexual abuse material (CSAM). These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_CHILD_SAFETY_CSAM: &str = "tools.ozone.report.defs#reasonChildSafetyCSAM";
///Child endangerment. These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_CHILD_SAFETY_ENDANGERMENT: &str =
    "tools.ozone.report.defs#reasonChildSafetyEndangerment";
///Grooming or predatory behavior. These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_CHILD_SAFETY_GROOM: &str = "tools.ozone.report.defs#reasonChildSafetyGroom";
///Harassment or bullying of minors
pub const REASON_CHILD_SAFETY_HARASSMENT: &str =
    "tools.ozone.report.defs#reasonChildSafetyHarassment";
///Privacy violation involving a minor
pub const REASON_CHILD_SAFETY_MINOR_PRIVACY: &str =
    "tools.ozone.report.defs#reasonChildSafetyMinorPrivacy";
///Other child safety. These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_CHILD_SAFETY_OTHER: &str = "tools.ozone.report.defs#reasonChildSafetyOther";
///Promotion of child exploitation. These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_CHILD_SAFETY_PROMOTION: &str =
    "tools.ozone.report.defs#reasonChildSafetyPromotion";
///Disclosure & transparency violations
pub const REASON_CIVIC_DISCLOSURE: &str = "tools.ozone.report.defs#reasonCivicDisclosure";
///Electoral process violations
pub const REASON_CIVIC_ELECTORAL_PROCESS: &str =
    "tools.ozone.report.defs#reasonCivicElectoralProcess";
///Impersonation of electoral officials/entities
pub const REASON_CIVIC_IMPERSONATION: &str = "tools.ozone.report.defs#reasonCivicImpersonation";
///Voter intimidation or interference
pub const REASON_CIVIC_INTERFERENCE: &str = "tools.ozone.report.defs#reasonCivicInterference";
///Election misinformation
pub const REASON_CIVIC_MISINFORMATION: &str = "tools.ozone.report.defs#reasonCivicMisinformation";
///Doxxing
pub const REASON_HARASSMENT_DOXXING: &str = "tools.ozone.report.defs#reasonHarassmentDoxxing";
///Hate speech
pub const REASON_HARASSMENT_HATE_SPEECH: &str =
    "tools.ozone.report.defs#reasonHarassmentHateSpeech";
///Other harassing or hateful content
pub const REASON_HARASSMENT_OTHER: &str = "tools.ozone.report.defs#reasonHarassmentOther";
///Targeted harassment
pub const REASON_HARASSMENT_TARGETED: &str = "tools.ozone.report.defs#reasonHarassmentTargeted";
///Trolling
pub const REASON_HARASSMENT_TROLL: &str = "tools.ozone.report.defs#reasonHarassmentTroll";
///Fake account or bot
pub const REASON_MISLEADING_BOT: &str = "tools.ozone.report.defs#reasonMisleadingBot";
///Impersonation
pub const REASON_MISLEADING_IMPERSONATION: &str =
    "tools.ozone.report.defs#reasonMisleadingImpersonation";
///Harmful false claims
pub const REASON_MISLEADING_MISINFORMATION: &str =
    "tools.ozone.report.defs#reasonMisleadingMisinformation";
///Other misleading content
pub const REASON_MISLEADING_OTHER: &str = "tools.ozone.report.defs#reasonMisleadingOther";
///Scam
pub const REASON_MISLEADING_SCAM: &str = "tools.ozone.report.defs#reasonMisleadingScam";
///Spam
pub const REASON_MISLEADING_SPAM: &str = "tools.ozone.report.defs#reasonMisleadingSpam";
///Unlabelled gen-AI or synthetic content
pub const REASON_MISLEADING_SYNTHETIC_CONTENT: &str =
    "tools.ozone.report.defs#reasonMisleadingSyntheticContent";
///Banned user returning
pub const REASON_RULE_BAN_EVASION: &str = "tools.ozone.report.defs#reasonRuleBanEvasion";
///Other
pub const REASON_RULE_OTHER: &str = "tools.ozone.report.defs#reasonRuleOther";
///Promoting or selling prohibited items or services
pub const REASON_RULE_PROHIBITED_SALES: &str = "tools.ozone.report.defs#reasonRuleProhibitedSales";
///Hacking or system attacks
pub const REASON_RULE_SITE_SECURITY: &str = "tools.ozone.report.defs#reasonRuleSiteSecurity";
///Stolen content
pub const REASON_RULE_STOLEN_CONTENT: &str = "tools.ozone.report.defs#reasonRuleStolenContent";
///Adult sexual abuse content
pub const REASON_SEXUAL_ABUSE_CONTENT: &str = "tools.ozone.report.defs#reasonSexualAbuseContent";
///Animal sexual abuse
pub const REASON_SEXUAL_ANIMAL: &str = "tools.ozone.report.defs#reasonSexualAnimal";
///Deepfake adult content
pub const REASON_SEXUAL_DEEPFAKE: &str = "tools.ozone.report.defs#reasonSexualDeepfake";
///Non-consensual intimate imagery
pub const REASON_SEXUAL_NCII: &str = "tools.ozone.report.defs#reasonSexualNCII";
///Other sexual violence content
pub const REASON_SEXUAL_OTHER: &str = "tools.ozone.report.defs#reasonSexualOther";
///Sextortion
pub const REASON_SEXUAL_SEXTORTION: &str = "tools.ozone.report.defs#reasonSexualSextortion";
///Unlabelled adult content
pub const REASON_SEXUAL_UNLABELED: &str = "tools.ozone.report.defs#reasonSexualUnlabeled";
pub type ReasonType = String;
///Animal welfare violations
pub const REASON_VIOLENCE_ANIMAL_WELFARE: &str =
    "tools.ozone.report.defs#reasonViolenceAnimalWelfare";
///Extremist content. These reports will be sent only be sent to the application's Moderation Authority.
pub const REASON_VIOLENCE_EXTREMIST_CONTENT: &str =
    "tools.ozone.report.defs#reasonViolenceExtremistContent";
///Glorification of violence
pub const REASON_VIOLENCE_GLORIFICATION: &str =
    "tools.ozone.report.defs#reasonViolenceGlorification";
///Graphic violent content
pub const REASON_VIOLENCE_GRAPHIC_CONTENT: &str =
    "tools.ozone.report.defs#reasonViolenceGraphicContent";
///Other violent content
pub const REASON_VIOLENCE_OTHER: &str = "tools.ozone.report.defs#reasonViolenceOther";
///Self harm
pub const REASON_VIOLENCE_SELF_HARM: &str = "tools.ozone.report.defs#reasonViolenceSelfHarm";
///Threats or incitement
pub const REASON_VIOLENCE_THREATS: &str = "tools.ozone.report.defs#reasonViolenceThreats";
///Human trafficking
pub const REASON_VIOLENCE_TRAFFICKING: &str = "tools.ozone.report.defs#reasonViolenceTrafficking";
