// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `peerlink.profile.user` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///The user's arrival date (e.g., to the country/university).
    pub arrival_date: crate::types::string::Datetime,
    ///User's profile picture.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub avatar: core::option::Option<crate::types::BlobRef>,
    ///Specific campus life needs or preferences.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub campus_life_needs: core::option::Option<Vec<String>>,
    ///The user's country of origin/citizenship.
    pub country: String,
    ///Timestamp when the profile was created.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub created_at: core::option::Option<crate::types::string::Datetime>,
    ///A short bio or description.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub description: core::option::Option<String>,
    ///The user's display name.
    pub display_name: String,
    ///The user's handle.
    pub handle: crate::types::string::Handle,
    ///List of the user's hobbies and interests.
    pub hobbies: Vec<String>,
    ///The user's primary language.
    pub language: String,
    ///References to the user's previous posts.
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub previous_posts: core::option::Option<
        Vec<crate::com::atproto::repo::strong_ref::Main>,
    >,
    ///List of subjects the user is studying.
    pub study_subjects: Vec<String>,
}
pub type Record = crate::types::Object<RecordData>;
