// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Structs for ATP client, implements all HTTP APIs of XRPC.
///Client struct for the ATP service.
pub struct AtpServiceClient<T>
where
    T: atrium_xrpc::XrpcClient + Send + Sync,
{
    pub service: Service<T>,
}
impl<T> AtpServiceClient<T>
where
    T: atrium_xrpc::XrpcClient + Send + Sync,
{
    pub fn new(xrpc: T) -> Self {
        Self { service: Service::new(std::sync::Arc::new(xrpc)) }
    }
}
pub struct Service<T>
where
    T: atrium_xrpc::XrpcClient + Send + Sync,
{
    pub peerlink: peerlink::Service<T>,
    pub(crate) _phantom: core::marker::PhantomData<T>,
}
pub mod peerlink {
    pub struct Service<T>
    where
        T: atrium_xrpc::XrpcClient + Send + Sync,
    {
        pub(crate) xrpc: std::sync::Arc<T>,
        pub(crate) _phantom: core::marker::PhantomData<T>,
    }
}
impl<T> self::Service<T>
where
    T: atrium_xrpc::XrpcClient + Send + Sync,
{
    #[allow(unused_variables)]
    pub(crate) fn new(xrpc: std::sync::Arc<T>) -> Self {
        Self {
            #[cfg(feature = "namespace-peerlink")]
            peerlink: peerlink::Service::new(std::sync::Arc::clone(&xrpc)),
            _phantom: core::marker::PhantomData,
        }
    }
}
#[cfg(feature = "namespace-peerlink")]
impl<T> peerlink::Service<T>
where
    T: atrium_xrpc::XrpcClient + Send + Sync,
{
    #[allow(unused_variables)]
    pub(crate) fn new(xrpc: std::sync::Arc<T>) -> Self {
        Self { xrpc, _phantom: core::marker::PhantomData }
    }
    ///Get a user's PeerLink profile and associated data.
    pub async fn get_profile(
        &self,
        params: crate::peerlink::get_profile::Parameters,
    ) -> atrium_xrpc::Result<
        crate::peerlink::get_profile::Output,
        crate::peerlink::get_profile::Error,
    > {
        let response = self
            .xrpc
            .send_xrpc::<_, (), _, _>(&atrium_xrpc::XrpcRequest {
                method: http::Method::GET,
                nsid: crate::peerlink::get_profile::NSID.into(),
                parameters: Some(params),
                input: None,
                encoding: None,
            })
            .await?;
        match response {
            atrium_xrpc::OutputDataOrBytes::Data(data) => Ok(data),
            _ => Err(atrium_xrpc::Error::UnexpectedResponseType),
        }
    }
    ///Search for PeerLink users based on criteria.
    pub async fn search_users(
        &self,
        params: crate::peerlink::search_users::Parameters,
    ) -> atrium_xrpc::Result<
        crate::peerlink::search_users::Output,
        crate::peerlink::search_users::Error,
    > {
        let response = self
            .xrpc
            .send_xrpc::<_, (), _, _>(&atrium_xrpc::XrpcRequest {
                method: http::Method::GET,
                nsid: crate::peerlink::search_users::NSID.into(),
                parameters: Some(params),
                input: None,
                encoding: None,
            })
            .await?;
        match response {
            atrium_xrpc::OutputDataOrBytes::Data(data) => Ok(data),
            _ => Err(atrium_xrpc::Error::UnexpectedResponseType),
        }
    }
}
