// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!A collection of known record types.

#[cfg(feature = "namespace-peerlink")]
use crate::peerlink;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "$type")]
pub enum KnownRecord {
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.beacon.main")]
    PeerlinkBeaconMain(Box<peerlink::beacon::main::Record>),
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.chat.message")]
    PeerlinkChatMessage(Box<peerlink::chat::message::Record>),
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.feedback.main")]
    PeerlinkFeedbackMain(Box<peerlink::feedback::main::Record>),
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.mentor.intro")]
    PeerlinkMentorIntro(Box<peerlink::mentor::intro::Record>),
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.post.main")]
    PeerlinkPostMain(Box<peerlink::post::main::Record>),
    #[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
    #[cfg(feature = "namespace-peerlink")]
    #[serde(rename = "peerlink.profile.user")]
    PeerlinkProfileUser(Box<peerlink::profile::user::Record>),
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::beacon::main::Record> for KnownRecord {
    fn from(record: peerlink::beacon::main::Record) -> Self {
        KnownRecord::PeerlinkBeaconMain(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::beacon::main::RecordData> for KnownRecord {
    fn from(record_data: peerlink::beacon::main::RecordData) -> Self {
        KnownRecord::PeerlinkBeaconMain(Box::new(record_data.into()))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::chat::message::Record> for KnownRecord {
    fn from(record: peerlink::chat::message::Record) -> Self {
        KnownRecord::PeerlinkChatMessage(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::chat::message::RecordData> for KnownRecord {
    fn from(record_data: peerlink::chat::message::RecordData) -> Self {
        KnownRecord::PeerlinkChatMessage(Box::new(record_data.into()))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::feedback::main::Record> for KnownRecord {
    fn from(record: peerlink::feedback::main::Record) -> Self {
        KnownRecord::PeerlinkFeedbackMain(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::feedback::main::RecordData> for KnownRecord {
    fn from(record_data: peerlink::feedback::main::RecordData) -> Self {
        KnownRecord::PeerlinkFeedbackMain(Box::new(record_data.into()))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::mentor::intro::Record> for KnownRecord {
    fn from(record: peerlink::mentor::intro::Record) -> Self {
        KnownRecord::PeerlinkMentorIntro(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::mentor::intro::RecordData> for KnownRecord {
    fn from(record_data: peerlink::mentor::intro::RecordData) -> Self {
        KnownRecord::PeerlinkMentorIntro(Box::new(record_data.into()))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::post::main::Record> for KnownRecord {
    fn from(record: peerlink::post::main::Record) -> Self {
        KnownRecord::PeerlinkPostMain(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::post::main::RecordData> for KnownRecord {
    fn from(record_data: peerlink::post::main::RecordData) -> Self {
        KnownRecord::PeerlinkPostMain(Box::new(record_data.into()))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::profile::user::Record> for KnownRecord {
    fn from(record: peerlink::profile::user::Record) -> Self {
        KnownRecord::PeerlinkProfileUser(Box::new(record))
    }
}
#[cfg_attr(docsrs, doc(cfg(feature = "namespace-peerlink")))]
#[cfg(feature = "namespace-peerlink")]
impl From<peerlink::profile::user::RecordData> for KnownRecord {
    fn from(record_data: peerlink::profile::user::RecordData) -> Self {
        KnownRecord::PeerlinkProfileUser(Box::new(record_data.into()))
    }
}
