// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.graph.getStarterPacksWithMembership` namespace.
pub const NSID: &str = "app.bsky.graph.getStarterPacksWithMembership";
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct ParametersData {
    ///The account (actor) to check for membership.
    pub actor: crate::types::string::AtIdentifier,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub limit: core::option::Option<crate::types::LimitedNonZeroU8<100u8>>,
}
pub type Parameters = crate::types::Object<ParametersData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct OutputData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub cursor: core::option::Option<String>,
    pub starter_packs_with_membership: Vec<StarterPackWithMembership>,
}
pub type Output = crate::types::Object<OutputData>;
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(tag = "error", content = "message")]
pub enum Error {}
impl std::fmt::Display for Error {
    fn fmt(&self, _f: &mut std::fmt::Formatter) -> std::fmt::Result {
        Ok(())
    }
}
///A starter pack and an optional list item indicating membership of a target user to that starter pack.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct StarterPackWithMembershipData {
    #[serde(skip_serializing_if = "core::option::Option::is_none")]
    pub list_item: core::option::Option<crate::app::bsky::graph::defs::ListItemView>,
    pub starter_pack: crate::app::bsky::graph::defs::StarterPackView,
}
pub type StarterPackWithMembership = crate::types::Object<StarterPackWithMembershipData>;
