// @generated - This file is generated by atrium-codegen. DO NOT EDIT.
//!Definitions for the `app.bsky.notification.declaration` namespace.
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct RecordData {
    ///A declaration of the user's preference for allowing activity subscriptions from other users. Absence of a record implies 'followers'.
    pub allow_subscriptions: String,
}
pub type Record = crate::types::Object<RecordData>;
